// Package @bunvex/core — the engine. See ARCHITECTURE.md for what lives where.

export { bundledModule, provideBundledModules } from "./bundled-modules.ts";
export {
  CRON_JOB_LOGS_TABLE,
  CRON_JOBS_TABLE,
  CRON_NEXT_RUN_TABLE,
  ENVIRONMENT_VARIABLES_TABLE,
  EXPORTS_TABLE,
  IndexBackfillingError,
  IndexStagedError,
  type IndexState,
  MODULES_TABLE,
  SCHEDULED_FUNCTIONS_TABLE,
  SCHEMAS_TABLE,
  SNAPSHOT_IMPORTS_TABLE,
  SOURCE_PACKAGES_TABLE,
  STORAGE_DELETIONS_TABLE,
  STORAGE_TABLE,
  UDF_CONFIG_TABLE,
} from "./catalog.ts";
export {
  Committer,
  CommitterStoppedError,
  type Conflict,
  ConflictError,
  commitWriteBytes,
  type FlushRetryOptions,
  firstOverlap,
  type Interval,
  type LogEntry,
  logEntryBytes,
  MAX_TRANSACTION_WINDOW_US,
  OutOfRetentionError,
  overlaps,
  WRITE_BATCH_MAX_BYTES,
  WRITE_BATCH_MAX_DOCUMENTS,
  WRITE_LOG_HARD_MAX_BYTES,
  WRITE_LOG_MAX_RETENTION_US,
  WRITE_LOG_MIN_RETENTION_US,
  WRITE_LOG_SOFT_MAX_SIZE_BYTES,
  WRITE_RETRY_INITIAL_BACKOFF_MS,
  WRITE_RETRY_MAX_BACKOFF_MS,
  type WriteBatchLimits,
  type WriteLogRetention,
} from "./committer.ts";
export type {
  AnyDataModel,
  BetterOmit,
  DataModelFromSchemaDefinition,
  DocumentByInfo,
  DocumentByName,
  FieldPaths,
  GenericDataModel,
  GenericDocument,
  GenericFieldPaths,
  GenericTableInfo,
  IdField,
  Indexes,
  IndexNames,
  NamedIndex,
  NamedTableInfo,
  SystemFields,
  SystemIndexes,
  SystemTableNames,
  TableNamesInDataModel,
  WithOptionalSystemFields,
  WithoutSystemFields,
} from "./data-model.ts";
export type {
  BaseDatabaseReader,
  ExpressionOrValueOf,
  FieldTypeFromFieldPath,
  FilterBuilder,
  GenericDatabaseReader,
  GenericDatabaseWriter,
  IndexRange,
  IndexRangeBuilder,
  LowerBoundIndexRangeBuilder,
  OrderedQuery,
  PaginationResultOf,
  PatchValue,
  Query,
  QueryInitializer,
  SystemDataModel,
  UpperBoundIndexRangeBuilder,
} from "./database-types.ts";
export {
  checkUserTime,
  type ExecutionKind,
  failExecution,
  formatDuration,
  installDeterminismIn,
  newUserTimer,
  observeTime,
  pausingUserTime,
  runImportPhase,
  SYSTEM_TIMEOUT_MESSAGE,
  type UserTimer,
  wallClock,
  withUserTimer,
} from "./determinism.ts";
export {
  type CacheCompanion,
  type Caller,
  type CallRequest,
  DEFAULT_INSTANCE_NAME,
  Engine,
  INDEX_BACKFILL_DEFAULTS,
  type IndexBackfillOptions,
  OCC_INITIAL_BACKOFF_MS,
  OCC_MAX_BACKOFF_MS,
  OCC_MAX_RETRIES,
  OccError,
  occBackoffMs,
  parseValue,
  type QueryJournal,
  readInstanceRecord,
  readSystemRows,
  SchemaPushError,
  stringifyValue,
  type TxBody,
} from "./engine.ts";
export {
  checkEnvVarName,
  checkEnvVarValue,
  ENV_VAR_LIMIT,
  ENV_VAR_NAME_MAX_LENGTH,
  ENV_VAR_TOTAL_SIZE_LIMIT,
  ENV_VAR_VALUE_MAX_LENGTH,
  EnvironmentVariableError,
  EnvironmentVariables,
  type EnvVarChange,
} from "./environment-variables.ts";
export { Expression, type ExpressionOrValue, filterBuilder } from "./filter.ts";
export { instanceSecretBytes, kbkdfCtrHmacSha256 } from "./kbkdf.ts";
export { compareKeys, encodeKey, type KeyValue, prefixEnd } from "./keyenc.ts";
export {
  DatabaseTimeoutError,
  type DocLogRow,
  type DocPrune,
  type DocWrite,
  hasLease,
  hasRetention,
  type IndexPrune,
  type IndexWrite,
  LAYOUT_VERSION,
  LayoutError,
  type Lease,
  type LeaseAcquire,
  LeaseHeldError,
  LeaseLostError,
  type LogCommit,
  type OpenOptions,
  type Persistence,
  ReadOnlyError,
  type ReadOnlyFlag,
  type RetentionStore,
  type ScanDocs,
  UnsureCommitError,
} from "./persistence/index.ts";
export { MAX_CACHE_AGE_MS, QUERY_CACHE_MAX_BYTES, QueryCache } from "./query-cache.ts";
export { type IndexPoint, ReadSetIndex } from "./read-set-index.ts";
export { RETENTION_GLOBALS, Retention, type RetentionOptions } from "./retention.ts";
export {
  cancelJob,
  completeJob,
  deleteCompletedJobs,
  dueJobs,
  getJob,
  insertJob,
  isJobId,
  type JobDoc,
  type JobState,
  nextJobTs,
  type PublicJob,
  patchJob,
  publicJob,
  TRANSACTION_MAX_NUM_SCHEDULED,
  TRANSACTION_MAX_SCHEDULED_TOTAL_ARGUMENT_SIZE_BYTES,
} from "./scheduled-jobs.ts";
export {
  type DeclaredTable,
  type Doc,
  defineSchema,
  defineTable,
  type Expand,
  type FieldValue,
  type GenericSchema,
  type GenericTableIndexes,
  type GenericTableSearchIndexes,
  type IndexDef,
  indexKey,
  MAX_INDEXES_PER_TABLE,
  MAX_SEARCH_FILTER_FIELDS,
  type SchemaDefinition,
  type SearchIndexDef,
  type TableDef,
  TableDefinition,
} from "./schema.ts";
export {
  type SchemaJson,
  type SearchIndexJson,
  schemaFromJson,
  schemaToJson,
  type TableJson,
} from "./schema-json.ts";
export {
  SESSION_CLEANUP_CHUNK,
  SESSION_CLEANUP_ROWS_PER_SECOND,
  SESSION_REQUEST_RETENTION_MS,
  type SessionRequestId,
  type SessionRequestOutcome,
} from "./session-requests.ts";
export { SystemReader } from "./system-reader.ts";
export {
  ImportIdError,
  type PaginationOptions,
  type PaginationResult,
  type Savepoint,
  Tx,
  type TxLimits,
  type TxQuery,
} from "./tx.ts";
